### ISSUE TITLE
IndexedDB adapter?

### ISSUE THREAD

**Issue by nolanlawson** [arthurhsu/rdb-polyfill#5]
I came across this repo because we were discussing what an RDB polyfill might look like, and I was pleasantly surprised to see you'd been working on one! :smiley: If I hadn't seen this, I might have started writing my own.

One question, though: have you considered what it might look like to support multiple adapters in this project? E.g. an IndexedDB adapter in addition to the current SQLite one?

Reason I ask is because one goal I might have with such a polyfill is to actually make it work over IndexedDB. This would serve two purposes:

1. Having a true polyfill, i.e. to support browsers that don't have native RDB (which is an extremely valuable thing to have, assuming RDB becomes an actual browser API)
2. Exposing performance problems with implementing such a polyfill over IDB. In other words, if one can implement RDB over IDB without any perf problems, then there's little reason for a native RDB implementation to exist. But if there are serious performance problems (e.g. the whole thing needs to be implemented in-memory and merely flushed to IDB) then that makes a great case for a native RDB browser API.

Anyway, nice work on this, and I'm going to be interested to peruse the source code. :smile:

**Comment by arthurhsu** [comment]
Main bottleneck is that there's not an easy way to support DDL, and I really don't want to write the whole SQL engine again in TypeScript since IndexedDB does not support long-lived transaction. The other option is to use WebAssembly to compile SQLite, which uses IndexedDB as a file system.

I think an easier alternative is to use Electron and plug in native C++ calls. Given my experience with Visual Studio Code (yeah this repo is developed using that), this option looks very attractive. Ideally I can directly construct SQL syntax tree and pass to the lower level engine, so I can totally rip the SQL parser (which is also a big chunk in SQL engine). At that moment a benchmark will be very persuasive since that's how browser vendors should have implemented. Moreover, even if this spec does not fly, at least I have some really useful library for the Electro community.
